services:
  # FastAPI アプリケーションサービス (APIサーバー)
  api_service:
    build:
      context: ./api_service # FastAPIアプリのコードがあるディレクトリ
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000" # ホストOSのポート:コンテナのポート
    volumes:
      - ./api_service:/usr/src/python # ホストの./api_serviceをコンテナの/usr/src/pythonにマウント
    depends_on: # 起動順序の制御
      - db_service
      - ai_service  
    networks: # サービス間通信用のネットワーク
      - app_network
    environment:
      - AI_SERVICE_URL=http://ai_service:5001 # AIサービスのエンドポイント

  # Python AIサービス (画像認識など)
  ai_service:
    build:
      context: ./ai_service # AIアプリのコードがあるディレクトリ
      dockerfile: Dockerfile
    container_name: ai_service
    hostname: ai_service # コンテナ内でのホスト名
    ports: # (開発時や外部から直接アクセスする場合)
      - "5001:5001" # FastAPIと重複しないポート
    volumes:
      - ./ai_service:/usr/src/python # ホストの./ai_serviceをコンテナの/usr/src/pythonにマウント
      # (もしモデルをマウントするなら)
      # - ./ai_service/model:/ai_app/model:ro
    networks:
      - app_network

  # MySQL データベースサービス
  db_service:
    image: mysql:8.4
    container_name: db_service
    hostname: db_service
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # rootユーザーのパスワード
      MYSQL_DATABASE: database # デフォルトのデータベース名
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql # MySQLのデータ永続化
      - ./mysql/conf.d:/etc/mysql/conf.d #2025/06/13ホストのディレクトリをコンテナにマウント
      - ./csv:/mnt/csv # CSVファイルをコンテナ内の/csvにマウント
    networks:
      - app_network

  # MySQL 管理ツール (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    # platform: linux/arm64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db_service
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db_service
    networks:
      - app_network

# ボリュームの定義 (データの永続化)
volumes:
  mysql-data:
    driver: local

# ネットワークの定義 (サービス間の名前解決と通信を可能にする)
networks:
  app_network:
    driver: bridge