services:
  backend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_service
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    networks:
      - app_network

  # MySQL データベースサービス
  db_service:
    image: mysql:8.4
    container_name: db_service
    hostname: db_service
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root # rootユーザーのパスワード
      MYSQL_DATABASE: gomimi # デフォルトのデータベース名
      MYSQL_USER: guest # ゲストユーザー
      MYSQL_PASSWORD: 3923
    volumes:
      - mysql-data:/var/lib/mysql # MySQLのデータ永続化
      # - ./mysql/conf.d:/etc/mysql/conf.d #2025/06/13ホストのディレクトリをコンテナにマウント
      # - ./csv:/mnt/csv # CSVファイルをコンテナ内の/csvにマウント
    networks:
      - app_network

  # MySQL 管理ツール (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    # platform: linux/arm64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db_service
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db_service
    networks:
      - app_network

# ボリュームの定義 (データの永続化)
volumes:
  mysql-data:
    driver: local

# ネットワークの定義 (サービス間の名前解決と通信を可能にする)
networks:
  app_network:
    driver: bridge