services:
  # FastAPI アプリケーションサービス (APIサーバー)
  api_service:
    build:
      context: ./api_service # FastAPIアプリのコードがあるディレクトリ
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000" # ホストOSのポート:コンテナのポート
    volumes:
      - ./api_service:/usr/src/python # ホストの./api_serviceをコンテナの/usr/src/pythonにマウント
    depends_on: # 起動順序の制御
      - db_service
      - ai_service  
    networks: # サービス間通信用のネットワーク
      - app_network
    environment:
      - AI_SERVICE_URL=http://ai_service:5001 # AIサービスのエンドポイント

  # Python AIサービス (画像認識など)
  ai_service:
    build:
      context: ./ai_service # AIアプリのコードがあるディレクトリ
      dockerfile: Dockerfile
    container_name: ai_service
    hostname: ai_service # コンテナ内でのホスト名
    ports: # (開発時や外部から直接アクセスする場合)
      - "5001:5001" # FastAPIと重複しないポート
    volumes:
      - ./ai_service:/usr/src/python # ホストの./ai_serviceをコンテナの/usr/src/pythonにマウント
      # (もしモデルをマウントするなら)
      # - ./ai_service/model:/ai_app/model:ro
    networks:
      - app_network

  # MongoDB データベースサービス
  # db_service:
  #   build: ./database # MongoDBのDockerfileがあるディレクトリ
  #   container_name: db_service
  #   hostname: db_service # コンテナ内でのホスト名
  #   # restart: always # コンテナが停止した場合に自動再起動
  #   ports:
  #     - "27017:27017" # (開発時) ホストから直接MongoDBにアクセスする場合
  #   volumes:
  #     - ./database/db_data:/data/db # 名前付きボリュームでデータを永続化
  #     - ./database/configdb:/data/configdb # MongoDBの設定データ用
  #   networks:
  #     - app_network

  db_service:
    image: mongo:latest
    container_name: db_service
    hostname: db_service
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database/db_data:/data/db
      - ./database/configdb:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app_network


  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db_service
    depends_on:
      - db_service
    networks:
      - app_network

# ボリュームの定義 (データの永続化)
volumes:
  db_data: # DBのデータ用
    driver: local
  configdb: # MongoDBの設定データ用
    driver: local

# ネットワークの定義 (サービス間の名前解決と通信を可能にする)
networks:
  app_network:
    driver: bridge